//
// Created by andy on 29/1/21.
//

#ifndef TP_WOLFENSTEIN_IMAGES_H
#define TP_WOLFENSTEIN_IMAGES_H

#define INVALID_IMAGE 0
#define GRAY_WALL 1
#define BLUE_WALL 2
#define BROWN_WALL 3
#define STONE_WALL 4

#define ITEM_CHAIN_CANNON 5
#define ITEM_ROCKET_LAUNCHER 6
#define ITEM_MACHINE_GUN 7
#define ITEM_KEY 8
#define ITEM_CUP 9
#define ITEM_CROWN 10
#define ITEM_CHEST 11
#define ITEM_CROSS 12
#define ITEM_MEDICAL_KIT 13
#define ITEM_BULLETS 14
#define ITEM_BLOOD 15

#define ENEMY_DOG 16
#define ENEMY_GUARD 17
#define ENEMY_SS 18
#define ENEMY_OFFICER 19
#define ENEMY_MUTANT 20

#define WEAPON_KNIFE 21
#define WEAPON_PISTOL 22
#define WEAPON_MACHINE_GUN 23
#define WEAPON_ROCKET_LAUNCHER 24
#define WEAPON_CHAIN_CANNON 25

#define UI_KNIFE 26
#define UI_PISTOL 27
#define UI_MACHINE_GUN 28
#define UI_ROCKET_LAUNCHER 29
#define UI_CHAIN_CANNON 30

#define EFFECT_EXPLOSION 31

#define MISC



#endif //TP_WOLFENSTEIN_IMAGES_H
