#ifndef WOLFENSTEIN3D_SERVER_MENU_EVENTS_H
#define WOLFENSTEIN3D_SERVER_MENU_EVENTS_H

#define CREATE_GAME "0"
#define JOIN_GAME "1"
#define SUCCESS "2"
#define ERROR "3"
#define BACK "4"

#endif //WOLFENSTEIN3D_SERVER_MENU_EVENTS_H
