//
// Created by andy on 22/2/21.
//

#ifndef TP_WOLFENSTEIN_TIMED_EVENTS_H
#define TP_WOLFENSTEIN_TIMED_EVENTS_H

#define WEAPON_SHOOTING_ANIMATION_TURNS 3
#define MACHINE_GUN_ANIMATION_TURNS 20
#define ENEMY_DEATH_ANIMATION_TURNS 1
#define ENEMY_ATTACKING_ANIMATION_TURNS 1
#define BLOOD_EFFECT_ANIMATION_TURNS 3
#define EXPLOSION_ANIMATION_TURNS 3

#endif //TP_WOLFENSTEIN_TIMED_EVENTS_H
