#ifndef TP_WOLFENSTEIN_CHANGES_H
#define TP_WOLFENSTEIN_CHANGES_H

#define REMOVE_POSITIONABLE 0
#define MOVE_PLAYER 1
#define CHANGE_POINTS 2
#define CHANGE_HP 3
#define CHANGE_AMMO 4
#define CHANGE_WEAPON 5
#define ADD_KEY 6
#define ADD_WEAPON 7
#define LOSE_LIFE 8
#define DEATH_PLAYER 9
#define DEATH_RESPAWN_PLAYER 10
#define RPG_SHOOT 11
#define ADD_PLAYER 12
#endif //TP_WOLFENSTEIN_CHANGES_H
