#ifndef TP_WOLFENSTEIN_CHANGES_H
#define TP_WOLFENSTEIN_CHANGES_H

#define INVALID (-1)
#define REMOVE_POSITIONABLE 0
#define MOVE_PLAYER 1
#define CHANGE_POINTS 2
#define CHANGE_HP 3
#define CHANGE_AMMO 4
#define CHANGE_WEAPON 5
#define KILL_PLAYER 6
#define RESPAWN_PLAYER 7
#define ADD_PLAYER 8
#define ADD_BULLETS_AT 9
#define ADD_KEY_AT 10
#define ADD_MACHINE_GUN_AT 11
#define ADD_CHAIN_GUN_AT 12
#define ADD_RPG_GUN_AT 13
#define PLAYER_USE_KEY 14
#define ADD_UNLOCKED_DOOR 15
#define RPG_MOVE_TO 16
#define RPG_EXPLODE_AT 17

#endif //TP_WOLFENSTEIN_CHANGES_H
