#ifndef TP_WOLFENSTEIN_EVENTS_H
#define TP_WOLFENSTEIN_EVENTS_H

#define INVALID 0
#define CONNECT_PLAYER 1
#define MOVE_PLAYER 2
#define SHOOT 3
#define OPEN_DOOR 4
#define PUSH_WALL 5
#define TURN_CAMERA 6
#define CHANGE_GUN 7
#define PLAYER_READY 8

#define MOVE_LEFT 0
#define MOVE_RIGHT 1
#define MOVE_UP 2
#define MOVE_DOWN 3
#define CAMERA_LEFT 1
#define CAMERA_RIGHT (-1)

#endif //TP_WOLFENSTEIN_EVENTS_H
