#ifndef TP_WOLFENSTEIN_MAP_ITEM_IDENTIFIERS_H
#define TP_WOLFENSTEIN_MAP_ITEM_IDENTIFIERS_H

#define MAP_STONE_WALL 1
#define MAP_WOOD_WALL 2
#define MAP_BLUE_WALL 3
#define MAP_ROCK_WALL 4
#define MAP_LOCKED_DOOR 5
#define MAP_UNLOCKED_DOOR 6
#define MAP_BARREL 7
#define MAP_TABLE 8
#define MAP_FOOD 9
#define MAP_MEDKIT 10
#define MAP_WATER_PUDDLE 11
#define MAP_BULLETS 12
#define MAP_MACHINE_GUN 13
#define MAP_CHAIN_GUN 14
#define MAP_RPG_GUN 15
#define MAP_KEY 16
#define MAP_CROSS 17
#define MAP_GOBLET 18
#define MAP_CHEST 19
#define MAP_CROWN 20

#endif //TP_WOLFENSTEIN_MAP_ITEM_IDENTIFIERS_H
