//
// Created by andy on 29/1/21.
//

#ifndef TP_WOLFENSTEIN_IMAGES_H
#define TP_WOLFENSTEIN_IMAGES_H

#define INVALID_IMAGE 0
#define GRAY_WALL 1
#define BLUE_WALL 2
#define BROWN_WALL 3
#define STONE_WALL 4
#define SILVER_DOOR 5

#define ITEM_CHAIN_CANNON 6
#define ITEM_ROCKET_LAUNCHER 7
#define ITEM_MACHINE_GUN 8
#define ITEM_KEY 9
#define ITEM_CUP 10
#define ITEM_CROWN 11
#define ITEM_CHEST 12
#define ITEM_CROSS 13
#define ITEM_MEDICAL_KIT 14
#define ITEM_BULLETS 15
#define ITEM_BLOOD 16
#define ITEM_FOOD 17

#define ENEMY_DOG 18
#define ENEMY_GUARD 19
#define ENEMY_SS 20
#define ENEMY_OFFICER 21
#define ENEMY_MUTANT 22

#define WEAPON_KNIFE 23
#define WEAPON_PISTOL 24
#define WEAPON_MACHINE_GUN 25
#define WEAPON_ROCKET_LAUNCHER 26
#define WEAPON_CHAIN_CANNON 27

#define UI_KNIFE 28
#define UI_PISTOL 29
#define UI_MACHINE_GUN 30
#define UI_ROCKET_LAUNCHER 31
#define UI_CHAIN_CANNON 32

#define EFFECT_EXPLOSION 33

#define MISC_BARREL 34
#define MISC_TABLE 35



#endif //TP_WOLFENSTEIN_IMAGES_H
