//
// Created by andy on 29/1/21.
//

#ifndef TP_WOLFENSTEIN_IMAGES_H
#define TP_WOLFENSTEIN_IMAGES_H

#define INVALID_IMAGE 0
#define GRAY_WALL 1
#define BLUE_WALL 2
#define BROWN_WALL 3
#define STONE_WALL 4
#define FAKE_WALL 5
#define UNLOCKED_DOOR 6
#define LOCKED_DOOR 7
#define SILVER_DOOR 8

#define ITEM_CHAIN_CANNON 9
#define ITEM_ROCKET_LAUNCHER 10
#define ITEM_MACHINE_GUN 11
#define ITEM_KEY 12
#define ITEM_GOBLET 13
#define ITEM_CROWN 14
#define ITEM_CHEST 15
#define ITEM_CROSS 16
#define ITEM_MEDICAL_KIT 17
#define ITEM_BULLETS 18
#define ITEM_BLOOD 19
#define ITEM_FOOD 20

#define ENEMY_DOG 21
#define ENEMY_GUARD 22
#define ENEMY_SS 23
#define ENEMY_OFFICER 24
#define ENEMY_MUTANT 25

#define SCREEN_WEAPON_KNIFE 26
#define SCREEN_WEAPON_PISTOL 27
#define SCREEN_WEAPON_MACHINE_GUN 28
#define SCREEN_WEAPON_CHAIN_CANNON 29
#define SCREEN_WEAPON_ROCKET_LAUNCHER 30

#define UI_KNIFE_ICON 31
#define UI_PISTOL_ICON 32
#define UI_MACHINE_GUN_ICON 33
#define UI_CHAIN_CANNON_ICON 34
#define UI_ROCKET_LAUNCHER_ICON 35

#define EFFECT_EXPLOSION 36
#define EFFECT_MISSILE 37
#define EFFECT_BLOOD 38
#define EFFECT_DOG_BLOOD 39

#define MISC_BARREL 40
#define MISC_TABLE 41
#define MISC_WATER 42

#define UI_PLAYER_FACE 43

#endif //TP_WOLFENSTEIN_IMAGES_H
