//
// Created by andy on 11/2/21.
//

#ifndef TP_WOLFENSTEIN_ITEM_TYPES_H
#define TP_WOLFENSTEIN_ITEM_TYPES_H

#define ITEM_TYPE_VERY_SMALL 0
#define ITEM_TYPE_SMALL 1
#define ITEM_TYPE_MEDIUM 2
#define ITEM_TYPE_LARGE 3
#define ITEM_TYPE_ELONGATED 4
#define ITEM_TYPE_SPREAD 5
#define ITEM_TYPE_ENEMY_HUMAN 6
#define ITEM_TYPE_ENEMY_DOG 7
#define ITEM_TYPE_WEAPON 8

#endif //TP_WOLFENSTEIN_ITEM_TYPES_H
