//
// Created by andy on 14/2/21.
//

#ifndef TP_WOLFENSTEIN_SCREEN_DRAWING_VALUES_H
#define TP_WOLFENSTEIN_SCREEN_DRAWING_VALUES_H

#define SCREEN_WIDTH 960
#define SCREEN_HEIGHT 600


#define PROJECTION_PLANE_WIDTH 960
#define PROJECTION_PLANE_HEIGHT 600
#define SCREEN_DRAWING_WIDTH 960
#define SCREEN_DRAWING_HEIGHT 0.8 * SCREEN_HEIGHT
#define SCREEN_WIDTH 960
#define FOV 60
#define WALL_HEIGHT 600
#define OBJECT_HEIGHT 600
#define VIEW_DIST 960
#define PROJECTION_PLANE_DISTANCE (SCREEN_DRAWING_WIDTH/2) / (tan(FOV/2))

#endif //TP_WOLFENSTEIN_SCREEN_DRAWING_VALUES_H
