//
// Created by andy on 14/2/21.
//

#ifndef TP_WOLFENSTEIN_SCREEN_DRAWING_VALUES_H
#define TP_WOLFENSTEIN_SCREEN_DRAWING_VALUES_H

#define FOV 60
#define WALL_HEIGHT 600
#define OBJECT_HEIGHT 600

#endif //TP_WOLFENSTEIN_SCREEN_DRAWING_VALUES_H
